widget_type: basebetterweather
fields:
  title: ""
  unit: ""
  dark_sky_temperature: ""
  dark_sky_humidity: ""
  dark_sky_precip_probability: ""
  dark_sky_precip_intensity: ""
  dark_sky_wind_speed: ""
  dark_sky_pressure: ""
  dark_sky_wind_bearing: ""
  dark_sky_apparent_temperature: ""
  dark_sky_icon: ""
  dark_sky_overnight_low_apparent_temperature: ""
  dark_sky_daytime_high_apparent_temperature: ""
css: []
static_css:
  title_style: $weather_sub_style
  unit_style: $weather_unit_style
  secondary_unit_style: $weather_secondary_unit_style
  temp_amp_min_icon_style: $weather_temp_amp_min_icon_style
  temp_amp_max_icon_style: $weather_temp_amp_max_icon_style
  temp_amp_min_style: $weather_temp_amp_min_style
  temp_amp_max_style: $weather_temp_amp_max_style
  precip_icon_style: $weather_precip_icon_style
  precip_style: $weather_precip_style
  main_style: $weather_main_style
  sub_style: $weather_sub_style
  widget_style: $weather_widget_style
icons: []
static_icons: []
