switch:
  platform: template
  switches:
    modect:
      friendly_name: Motion Detection
      value_template: "{{ is_state('group.modect', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.modect
      turn_off:
        service: homeassistant.turn_off
        entity_id: group.modect


shell_command:
  cam_snap: /scripts/hass.sh snap {{ cam }} /tmp/snap_{{ cam }}.jpg
  snap_upload: !secret snap_upload
  snap_ldelete: "rm -f /tmp/snap*.jpg"
  snap_rdelete: !secret snap_rdelete


script:
  snap_delete:
    alias: Delete snapshot
    sequence:
      - delay:
          minutes: 2
      - service: shell_command.snap_ldelete
      - service: shell_command.snap_rdelete

  snap_send_fb:
    alias: Send a CCTV picture
    sequence:
      # Disable ev. deletion job
      - service: script.turn_off
        data:
          entity_id: script.snap_delete
      - service: camera.snapshot
        data_template:
          entity_id: "camera.{{ camera }}"
          filename: "/tmp/snap.jpg"
      - service: shell_command.snap_upload
      - service: notify.html5
        data:
          message: Now facebook
      - service: notify.facebook
        data:
          target: !secret fb_my_phone_number
          message: Camera image
          data:
            attachment:
              type: image
              payload:
                url: !secret snap_public_url
      - service: notify.html5
        data:
          message: delete snapshot now
      - service: script.snap_delete


group:
  cameras_front_door:
    name: Front door cameras
    view: no
    entities:
      - camera.front_door
      - camera.doorpi

  cameras_terrace:
    name: Terrace Cameras
    view: no
    entities:
      - camera.terrace
      - camera.winpi

  cameras_living_room:
    name: Living Room Cameras
    view: no
    entities:
      - camera.c1

  cameras_office:
    name: Office Cameras
    view: no
    entities:
      - camera.hassistant

  cameras_misc:
    name: Other Cameras
    view: no
    entities:
      - camera.c2
      - camera.hallway

  cctv:
    name: CCTV
    view: no
    icon: mdi:camera-enhance
    entities:
      - sensor.bathroom_motion_motion_sensor
      - sensor.hallway_motion_motion_sensor
      - sensor.kitchen_motion_motion_sensor
      - sensor.toilet_motion_motion_sensor
      - group.c1
      - group.c2
      - group.raspicam_doorpi
      - group.raspicam_hassistant
      - group.raspicam_winpi
      - group.modect

  modect:
    name: Motion detection
    entities:
      - sensor.bathroom_motion_motion_sensor
      - sensor.hallway_motion_motion_sensor
      - sensor.kitchen_motion_motion_sensor
      - sensor.toilet_motion_motion_sensor
      - switch.foscam_c1_state
      - switch.foscam_c2_state
      - switch.doorpi_state
      - switch.hassistant_state
      - switch.winpi_state
      - switch.foscam_c1_modect
      - switch.foscam_c2_modect
      - switch.foscam_c1_sodect
      - switch.foscam_c2_sodect


homeassistant:
  customize:
    # Switches
    switch.modect:
      icon: mdi:camera-enhance

# vim: set filetype=yaml et sw=2 ts=2 :
