shell_command:
  refresh_plant_data: !secret cmd_plantgateway


script:
  refresh_plant_data:
    alias: Refresh plant data
    sequence:
      - service: shell_command.refresh_plant_data


automation:
  - alias: Refresh plant data on start and every 30min
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        minutes: 30
    action:
      - service: script.refresh_plant_data

  - alias: Miflora battery is low
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.lemon_battery, sensor.capsicum_annuum_battery, sensor.citrus_mitis_calamondin_battery, sensor.ficus_battery, sensor.croton_battery
        below: 15
    action:
      - service: notify.html5
        data_template:
          message: "Miflora battery is low on {{ trigger.to_state.attributes.friendly_name }}"



alert:
  plant_data_outdated:
    name: "The plant data is outdated"
    done_message: "Plant data is up to date"
    entity_id: binary_sensor.plant_data_outdated
    state: 'on'
    repeat: 86400
    can_acknowledge: True
    skip_first: False
    notifiers:
      - html5


binary_sensor:
  - platform: template
    sensors:
      plant_data_outdated:
        value_template: '{{ is_state("binary_sensor.capsicum_annuum_data_outdated", "on") and is_state("binary_sensor.pilea_data_outdated", "on") and is_state("binary_sensor.croton_data_outdated", "on") and is_state("binary_sensor.ficus_data_outdated", "on") and is_state("binary_sensor.lemon_data_outdated", "on") and is_state("binary_sensor.citrus_mitis_calamondin_data_outdated", "on") }}'
        friendly_name: 'Mi Flora Data Outdated'
      capsicum_annuum_data_outdated:
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.capsicum_annuum_last_updated.state) > 86400 }}'
        friendly_name: 'Capsicum Annuum Data Outdated'
      pilea_data_outdated:
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.pilea_last_updated.state) > 86400 }}'
        friendly_name: 'Pilea Data Outdated'
      croton_data_outdated:
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.croton_last_updated.state) > 86400 }}'
        friendly_name: 'Croton Data Outdated'
      ficus_data_outdated:
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.ficus_last_updated.state) > 86400 }}'
        friendly_name: 'Ficus Data Outdated'
      lemon_data_outdated:
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.lemon_last_updated.state) > 86400 }}'
        friendly_name: 'Lemon Data Outdated'
      citrus_mitis_calamondin_data_outdated:
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.citrus_mitis_calamondin_last_updated.state) > 86400 }}'
        friendly_name: 'Citrus Mitis Calamondin Data Outdated'


plant:
  Capsicum Annuum:
    sensors:
      moisture: sensor.capsicum_annuum_moisture
      battery: sensor.capsicum_annuum_battery
      temperature: sensor.capsicum_annuum_temperature
      conductivity: sensor.capsicum_annuum_conductivity
      brightness: sensor.capsicum_annuum_brightness
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 10
    min_temperature: 15
  Pilea:
    sensors:
      moisture: sensor.pilea_moisture
      battery: sensor.pilea_battery
      temperature: sensor.pilea_temperature
      conductivity: sensor.pilea_conductivity
      brightness: sensor.pilea_brightness
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 10
    min_temperature: 15
  Croton:
    sensors:
      moisture: sensor.croton_moisture
      battery: sensor.croton_battery
      temperature: sensor.croton_temperature
      conductivity: sensor.croton_conductivity
      brightness: sensor.croton_brightness
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 10
    min_temperature: 15
  Ficus Microcarpa:
    sensors:
      moisture: sensor.ficus_moisture
      battery: sensor.ficus_battery
      temperature: sensor.ficus_temperature
      conductivity: sensor.ficus_conductivity
      brightness: sensor.ficus_brightness
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 10
    min_temperature: 12
  Lemon Tree:
    sensors:
      moisture: sensor.lemon_moisture
      battery: sensor.lemon_battery
      temperature: sensor.lemon_temperature
      conductivity: sensor.lemon_conductivity
      brightness: sensor.lemon_brightness
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 10
    min_temperature: 0
  Citrus Mitis Calamondin:
    sensors:
      moisture: sensor.citrus_mitis_calamondin_moisture
      battery: sensor.citrus_mitis_calamondin_battery
      temperature: sensor.citrus_mitis_calamondin_temperature
      conductivity: sensor.citrus_mitis_calamondin_conductivity
      brightness: sensor.citrus_mitis_calamondin_brightness
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 10
    min_temperature: 5


sensor:
  - platform: mqtt
    name: capsicum_annuum_moisture
    state_topic: 'plants/mi/capsicum_annuum/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: capsicum_annuum_battery
    state_topic: 'plants/mi/capsicum_annuum/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: capsicum_annuum_temperature
    state_topic: 'plants/mi/capsicum_annuum/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: capsicum_annuum_conductivity
    state_topic: 'plants/mi/capsicum_annuum/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: capsicum_annuum_brightness
    state_topic: 'plants/mi/capsicum_annuum/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: capsicum_annuum_last_updated
    state_topic: 'plants/mi/capsicum_annuum/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: pilea_moisture
    state_topic: 'plants/mi/pilea/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: pilea_battery
    state_topic: 'plants/mi/pilea/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: pilea_temperature
    state_topic: 'plants/mi/pilea/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: pilea_conductivity
    state_topic: 'plants/mi/pilea/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: pilea_brightness
    state_topic: 'plants/mi/pilea/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: pilea_last_updated
    state_topic: 'plants/mi/pilea/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: croton_moisture
    state_topic: 'plants/mi/croton/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: croton_battery
    state_topic: 'plants/mi/croton/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: croton_temperature
    state_topic: 'plants/mi/croton/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: croton_conductivity
    state_topic: 'plants/mi/croton/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: croton_brightness
    state_topic: 'plants/mi/croton/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: croton_last_updated
    state_topic: 'plants/mi/croton/'
    value_template: '{{ value_json.timestamp }}'
  - platform: mqtt
    name: ficus_last_updated
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: ficus_moisture
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: ficus_battery
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: ficus_temperature
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: ficus_conductivity
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: ficus_brightness
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: lemon_moisture
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: lemon_battery
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: lemon_temperature
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: lemon_conductivity
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: lemon_brightness
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: lemon_last_updated
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: citrus_mitis_calamondin_last_updated
    state_topic: 'plants/mi/citrus_mitis_calamondin/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: citrus_mitis_calamondin_moisture
    state_topic: 'plants/mi/citrus_mitis_calamondin/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: citrus_mitis_calamondin_battery
    state_topic: 'plants/mi/citrus_mitis_calamondin/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: citrus_mitis_calamondin_temperature
    state_topic: 'plants/mi/citrus_mitis_calamondin/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: citrus_mitis_calamondin_conductivity
    state_topic: 'plants/mi/citrus_mitis_calamondin/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: citrus_mitis_calamondin_brightness
    state_topic: 'plants/mi/citrus_mitis_calamondin/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'



homeassistant:
  customize:
    group.all_plants:
      friendly_name: Plants
      hidden: false
    script.refresh_plant_data:
      icon: mdi:flower
    plant.capsicum_annuum:
      battery_friendly_name: "Miflora - Capsicum Annuum"
    plant.citrus_mitis_calamondin:
      battery_friendly_name: "Miflora - Citrus Mitis Calamondin"
    plant.pilea:
      battery_friendly_name: "Miflora - Pilea"
    plant.croton:
      battery_friendly_name: "Miflora - Croton"
    plant.ficus_microcarpa:
      battery_friendly_name: "Miflora - Ficus"
    plant.lemon_tree:
      battery_friendly_name: "Miflora - Lemon Tree"

# vim: set filetype=yaml et sw=2 ts=2 :
