joaoapps_join:
  - name: join
    api_key: !secret joaoapps_join_api_key
    device_names: !secret joaoapps_join_device_names


notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret notify_pushbullet_api_key

  - name: pushover
    platform: pushover
    api_key: !secret notify_pushover_api_key
    user_key: !secret notify_pushover_user_key

  - name: free_mobile
    platform: free_mobile
    username: !secret notify_free_username
    access_token: !secret notify_free_key

  - name: facebook
    platform: facebook
    page_access_token: !secret fb_page_token

  - name: facebook_me
    platform: group
    services:
      - service: facebook
        data:
          target: !secret fb_my_phone_number

  - name: facebook_her
    platform: group
    services:
      - service: facebook
        data:
          target: !secret fb_her_phone_number

  - name: twitter
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret

  - name: smsr
    platform: rest
    resource: http://octopi.lan:8090/sms
    method: POST
    message_param_name: msg
    target_param_name: to

  - name: html5
    platform: html5
    gcm_api_key: !secret fcm_server_key
    gcm_sender_id: !secret fcm_sender_id

  - name: speakcast
    platform: rest
    resource: http://nasteanas.lan:8993/speakcast
    method: POST
    message_param_name: msg
    # target_param_name: to  # set chromecast name/ip?

  - name: get_to_me
    platform: group
    services:
      - service: pushover
        data:
          data:
            priority: 2
            expire: 7200 # 2h
            retry: 900
      - service: free_mobile
      - service: smsr
        data:
          target: me

  - name: everybody
    platform: group
    services:
      - service: smsr
        data:
          target: me
      - service: smsr
        data:
          target: her

  - name: zanzito
    platform: zanzito
    device-name: nexus5x

  - name: zanzito_tts
    platform: group
    services:
      - service: zanzito
        data:
          data:
            say:

  - name: join
    platform: joaoapps_join
    api_key: !secret joaoapps_join_api_key
    device_names: !secret joaoapps_join_device_names

# vim: set filetype=yaml et sw=2 ts=2 :
