script:
  all_off:
    alias: All off
    sequence:
      - service: notify.zanzito_tts
        data:
          message: "Shutdown initiated."
      - service: light.turn_off
        data:
          entity_id: group.all_lights
      - service: script.turn_off_media_players
      - service: script.turn_off_office_tv
      - service: script.close_all_covers
      - service: script.turn_off_doorpi_screen
      - delay: '00:00:10'
      - service: script.turn_off_3d_printer

  bedtime:
    alias: Bedtime
    sequence:
      - service: script.zanzito_tts_say
        data:
          message: "Night."
      - service: scene.turn_on
        data:
          entity_id: scene.bedtime
      - service: script.lock_door
      - service: script.turn_off_office_tv
      - service: light.turn_off
        data:
          entity_id: group.office_lights
      - service: script.close_bedroom_covers
      - service: input_boolean.turn_on
        entity_id: input_boolean.dnd

  turn_off_mushu:
    alias: Turn off mushu via SSH
    sequence:
      - service: shell_command.turn_off_mushu

  turn_off_lights_if_we_are_away:
    alias: Turn off lights if we are away
    sequence:
      - condition: state
        entity_id: group.main_mobile_devices
        state: "not_home"
      - service: light.turn_off
        data:
          entity_id: group.all_lights


shell_command:
  turn_off_mushu: !secret cmd_shutdown_mushu


homeassistant:
  customize:
    script.all_off:
      can_cancel: False
      icon: mdi:nuke
    script.turn_off_media_players:
      icon: mdi:laptop-off

# vim: set filetype=yaml et sw=2 ts=2 :
