aftership_api_key: travis_secret_16
alarm_code: 0
android_ip_cam_g4p_hostname: 127.0.0.1
android_ip_cam_g4p_password: travis_secret_16
android_ip_cam_g4p_username: travis_secret_16
arlo_password: travis_secret_16
arlo_username: travis_secret_16
base_url: http://localhost:8080/index.html
cam_doorpi_password: travis_secret_16
cam_doorpi_username: travis_secret_16
cam_hassistant_password: travis_secret_16
cam_hassistant_username: travis_secret_16
cam_winpi_password: travis_secret_16
cam_winpi_username: travis_secret_16
cmd_doorpi_screen_state: travis_secret_16
cmd_octoprint_led_off: ./config/hass/.travis/file
cmd_octoprint_led_on: ./config/hass/.travis/file
cmd_octoprint_timelapse_rendering: travis_secret_16
cmd_plantgateway: travis_secret_16
cmd_shutdown_mushu: travis_secret_16
cmd_turn_off_doorpi_screen: travis_secret_16
cmd_turn_on_doorpi_screen: travis_secret_16
cmd_upspico_battery_level: travis_secret_16
cmd_upspico_power_state: travis_secret_16
darksky_api_key: travis_secret_16
db_url: travis_secret_16
emby_api_key: travis_secret_16
emby_host: travis_secret_16
fb_her_phone_number: 0
fb_my_phone_number: 0
fb_page_token: trav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3
fcm_sender_id: 0
fcm_server_key: travis_secret_16
flic_button_black_1: travis_secret_16
flic_button_black_2: travis_secret_16
flic_button_message_1: travis_secret_16
flic_button_message_2: travis_secret_16
flic_button_message_3: travis_secret_16
flic_button_white_1: travis_secret_16
flic_button_white_2: travis_secret_16
foscam_c1_hostname: travis_secret_16
foscam_c1_password: travis_secret_16
foscam_c1_username: travis_secret_16
foscam_c2_hostname: travis_secret_16
foscam_c2_password: travis_secret_16
foscam_c2_username: travis_secret_16
google_assistant_access_token: trav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav
google_assistant_api_key: travis_secret_16
google_assistant_client_id: travis_secret_16
google_assistant_project_id: travis_secret_16
google_home_bathroom: 127.0.0.1
google_home_kitchen: 127.0.0.1
google_home_living_room: 127.0.0.1
google_home_office: 127.0.0.1
google_maps_api_key: travis_secret_16
google_maps_password: travis_secret_16
google_maps_username: travis_secret_16
harmony_hub_device_altec_lansing_amp: 0
harmony_hub_device_living_room_tv: 0
harmony_hub_device_nvidia_shield_tv: 0
harmony_hub_device_orange_livebox_play_tv: 0
harmony_hub_device_sony_ps3: 0
home_elevation: 0
home_latitude: 0.0
home_longitude: 0.0
http_password: travis_secret_16
hue_bridge: 127.0.0.1
hue_sensor_bathroom_lux: http://localhost:8080/index.html
hue_sensor_bathroom_presence: http://localhost:8080/index.html
hue_sensor_bathroom_temp: http://localhost:8080/index.html
hue_sensor_hallway_lux: http://localhost:8080/index.html
hue_sensor_hallway_presence: http://localhost:8080/index.html
hue_sensor_hallway_temp: http://localhost:8080/index.html
hue_sensor_kitchen_lux: http://localhost:8080/index.html
hue_sensor_kitchen_presence: http://localhost:8080/index.html
hue_sensor_kitchen_temp: http://localhost:8080/index.html
hue_sensor_toilet_lux: http://localhost:8080/index.html
hue_sensor_toilet_presence: http://localhost:8080/index.html
hue_sensor_toilet_temp: http://localhost:8080/index.html
hue_token: trav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav
ifttt_key: travis_secret_16
influxdb_db: travis_secret_16
influxdb_host: 127.0.0.1
influxdb_password: travis_secret_16
influxdb_username: travis_secret_16
joaoapps_join_api_key: travis_secret_16
joaoapps_join_device_names: travis_secret_16
kleenex_message: travis_secret_16
lan_ipv4_addr: 127.0.0.1
lg_tv_mac_addr: 00:01:02:03:04:05
livebox_play_tv_setup_routing: travis_secret_16
mbiver_work_elevation: 0.0
mbiver_work_latitude: 0.0
mbiver_work_longitude: 0.0
mi_gw_api_key: travis_secret_16
mi_gw_mac: 00:01:02:03:04:05
miio_ir_device_id: 0
miio_ir_hostname: 127.0.0.1
miio_ir_token: trav1ss3cr3ttrav1ss3cr3ttrav1ss3
mqtt_broker: travis_secret_16
mqtt_cert: ./config/hass/.travis/file
mqtt_password: travis_secret_16
mqtt_username: travis_secret_16
nello_password: travis_secret_16
nello_username: travis_secret_16
notify_free_key: travis_secret_16
notify_free_username: 0
notify_pushbullet_api_key: travis_secret_16
notify_pushover_api_key: travis_secret_16
notify_pushover_user_key: travis_secret_16
nuki_bridge: 127.0.0.1
nuki_token: trav1ss3
nuki_web_token: trav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3
octoprint_api_key: travis_secret_16
octoprint_camera_url: http://localhost:8080/index.html
octoprint_host: travis_secret_16
octoprint_led_url: http://localhost:8080/index.html
openweathermap_api_key: travis_secret_16
owrt_password: travis_secret_16
owrt_username: travis_secret_16
player_kodi_password: travis_secret_16
player_kodi_username: travis_secret_16
postal_code: 0
roomba_hostname: travis_secret_16
roomba_password: travis_secret_16
roomba_username: 0
shell_cmd_setup_routing: travis_secret_16
shelly_bathroom_ceiling_password: travis_secret_16
shelly_bathroom_ceiling_resource: http://localhost:8080/index.html
shelly_bathroom_ceiling_username: travis_secret_16
shelly_project_nothing_password: travis_secret_16
shelly_project_nothing_resource: http://localhost:8080/index.html
shelly_project_nothing_username: travis_secret_16
sherlock_bike_password: travis_secret_16
sherlock_bike_username: travis_secret_16
smappee_client_id: travis_secret_16
smappee_host: travis_secret_16
smappee_local_password: travis_secret_16
smappee_password: travis_secret_16
smappee_secret: travis_secret_16
smappee_username: travis_secret_16
snap_public_url: http://localhost:8080/index.html
snap_rdelete: travis_secret_16
snap_upload: travis_secret_16
turris_password: travis_secret_16
turris_username: travis_secret_16
twitter_access_token: trav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttr
twitter_access_token_secret: trav1ss3cr3ttrav1ss3cr3ttrav1ss3cr3ttrav1ss3c
twitter_consumer_key: travis_secret_16
twitter_consumer_secret: travis_secret_16
voicerss_api_key: travis_secret_16
work_elevation: 0
work_latitude: 0.0
work_longitude: 0.0
wunderground_api_key: travis_secret_16
zabbix_password: travis_secret_16
zabbix_username: travis_secret_16
zm_hostname: travis_secret_16
zm_password: travis_secret_16
zm_username: travis_secret_16
